title: default

pages: false
delete: false

files:
  fields:
    caption:
      label: Description
      type: text

options: 
  delete: false
  status: false

fields: 
  title:
    label: Title
    type: title
    width: 1/1

  overviewBanner:
    label: Overview-Banner – Bild
    type: image
    width: 1/3

  bannerTextH1:
    label: Head1
    type: text
    width: 1/3

  bannerTextH5:
    label: Head5
    type: text
    width: 1/3
  
  introPHead:
    label: Einleitung
    type: headline
    numbered: false

  introHead:
    label: Titel
    type: text

  introText:
    label: Text
    type: textarea
    width: 1/2
    
  majors:
    label: Studiengänge
    type: structure
    style: table
    width: 1/2
    fields:
      title:
        label: Title
        type: text
      text:
        label: Text
        type: text
  
  hfgPHead:
    label: HfG – Schwäbisch Gmünd
    type: headline
    numbered: false

  hfgContainerImage:
    label: HfG-Container – Bild
    type: image
    width: 1/2

  hfgHead:
    label: Titel
    type: text
    width: 1/2

  hfgText1:
    label: Text1
    type: textarea
    width: 1/2

  hfgText2:
    label: Text2
    type: textarea  
    width: 1/2

  hfgBubbleImage:
    label: HfG-Bubble – Bild
    type: image

  hfgGallery:
    label: HfG-Gallery
    type: gallery

  ausstattungPHead:
    label: Ausstattung
    type: headline
    numbered: false

  ausstattungContainerImage:
    label: Ausstattung-Container – Bild
    type: image
    width: 1/2

  ausstattungHead:
    label: Titel
    type: text
    width: 1/2

  ausstattungText:
    label: Text
    type: textarea

  ausstattungGallery:
    label: Ausstattung-Gallery
    type: gallery

  engagiertPHead:
    label: Engagiert
    type: headline
    numbered: false

  engagiertContainerImage:
    label: Engagiert-Container – Bild
    type: image
    width: 1/2

  engagiertHead:
    label: Titel
    type: text
    width: 1/2

  engagiertText:
    label: Text
    type: textarea

  engagiertGallery:
    label: Engagiert-Gallery
    type: gallery

  fragenPHead:
    label: Fragen?
    type: headline
    numbered: false

  fragenContainerImage:
    label: Fragen-Container – Bild
    type: image
    width: 1/3

  fragenBubbleImage:
    label: Fragen-Bubble – Bild
    type: image
    width: 1/3

  fragenButtonText:
    label: Text
    type: text
    width: 1/3